DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);


DELETE FROM transactions;

DELETE FROM accounts;

ALTER TABLE accounts
  ADD COLUMN user_id INT UNIQUE NOT NULL REFERENCES users(id);
